runs: 3
seed: 42
datamodule:
  filename: /home/rjo21/Desktop/SuperSweetNet/data/pred_domain.tsv
  exp_name: ssn
  batch_size: 128
  num_workers: 16
  num_classes: 4
trainer:
  gpus: 1
  max_epochs: 100
  profiler: null
  gradient_clip_val: 100
model:
  arch: sweetnet
  hidden_dims: []
  graph_embed_dim: 256
  gin:
    node_feat_dim: 6
    node_embed_dim: 256
    num_gnn_layers: 3
  sweetnet:
    node_embed_dim: 128
    num_gnn_layers: 0
optimizer:
  module: adam
  lr: 0.001
  weight_decay: 0.01
  momentum: 0.01
  reduce_lr:
    factor: 0.1
    patience: 20
    monitor: val_loss
