runs: 1
seed: 42
datamodule:
  task: domain
  exp_name: ssn
  batch_size: 128
  num_workers: 16
  num_classes: 4
trainer:
  gpus: 1
  max_epochs: 1000
  profiler: null
  gradient_clip_val: 100
model:
  postfix: pure
  arch: gin
  hidden_dims: []
  graph_embed_dim: 256
  gin:
    node_feat_dim: 6
    node_embed_dim: 512
    num_gnn_layers: 3
  sweetnet:
    node_embed_dim: 256
    num_gnn_layers: 3
optimizer:
  module: adam
  lr: 0.0005
  weight_decay: 0.001
  momentum: 0.01
  reduce_lr:
    factor: 0.1
    patience: 20
    monitor: loss
